export const categories = [
  'All',
  'Mobile Covers',
  'Tuffon Glasses',
  'Head Phones',
  'Chargers',
  'USB',
  'OTG Cable',
  'Screen Casting',
  'Selfie Sticks',
  'Bluetooth Earbuds',
  'Car Mounts',
  'Smartwatches',
  'Gaming Controllers',
  'Skins',
  'Phone Ring Holder',
];

export const products = [
  {
    id: '1',
    name: 'Real me Narzo 20 pro mobile cover',
    image: require('../assets/mobile_covers.png'),
    price: 200,
    category: ['Mobile Covers'],
    quantity: 3,
    status: 'pending',
    date: new Date(),
  },
  {
    id: '2',
    name: 'Blutooth Headphone',
    image: require('../assets/headephones.png'),
    price: 2000,
    category: ['Head Phones'],
    quantity: 1,
    status: 'cancel',
    date: new Date(),
  },
  {
    id: '3',
    name: 'Oppo Mobile Cover Ring',
    image: require('../assets/oppo_ring.png'),
    price: 50,
    category: ['Phone Ring Holder'],
    quantity: 5,
    status: 'success',
    date: new Date(),
  },
  {
    id: '4',
    name: 'car mount for any mobile',
    image: require('../assets/car_mount.png'),
    price: 300,
    category: ['Car Mounts'],
    quantity: 3,
    status: 'success',
    date: new Date(),
  },
  {
    id: '5',
    name: 'Otg cable',
    image: require('../assets/otg.png'),
    price: 1000,
    category: ['OTG Cable'],
    quantity: 1,
    status: 'pending',
    date: new Date(),
  },
  {
    id: '6',
    name: 'Sandisk pendrive of 16gb',
    image: require('../assets/usb.png'),
    price: 400,
    category: ['OTG Cable', 'USB'],
    quantity: 10,
    status: 'cancel',
    date: new Date(),
  },
  {
    id: '7',
    name: 'Smart watch',
    image: require('../assets/smart_watch.png'),
    price: 1500,
    category: ['Smartwatches'],
    quantity: 3,
    status: 'pending',
    date: new Date(),
  },
  {
    id: '8',
    name: 'Mobile cover',
    image: require('../assets/selfie_stick.png'),
    price: 4000,
    category: ['Selfie Sticks'],
    quantity: 9,
    status: 'success',
    date: new Date(),
  },
];

export const deliveryAddress = [
  {
    id: '1',
    name: 'Pratik Panchal',
    address:
      'Gandhi n tya, Rathod na sasariya ni baju ma, Lal Darwaja, Patan, Gujarat, 384265',
  },
  {
    id: '2',
    name: 'Parshv Shah',
    address: 'Khearvasi, Blood Bank, Patan, Gujarat, 384265',
  },
  {
    id: '3',
    name: 'Karan Rajpurohit',
    address: 'Gom na chede, Patan, Gujarat, 384265',
  },
  {
    id: '4',
    name: 'Meet Rathod',
    address: 'Ambaji Neliyu, Patan, Gujarat, 384265',
  },
  {
    id: '5',
    name: 'Nisarg Patel',
    address: 'Chindiya, Known as Paris, Patan, Gujarat, 384265',
  },
  {
    id: '6',
    name: 'Yuvraj Vaghela',
    address: 'Harij ni baju na gomde, Patan, Gujarat, 384265',
  },
];

export const savedCards = [
  {
    id: '1',
    cardNum: '2948',
    cardExpiry: '12/23',
    cardType: 'Visa',
  },
  {
    id: '2',
    cardNum: '8956',
    cardExpiry: '09/23',
    cardType: 'Master',
  },
  {
    id: '3',
    cardNum: '9623',
    cardExpiry: '02/26',
    cardType: 'Maestro',
  },
  {
    id: '4',
    cardNum: '1648',
    cardExpiry: '12/23',
    cardType: 'Rupay',
  },
  {
    id: '5',
    cardNum: '6912',
    cardExpiry: '11/25',
    cardType: 'Rupay',
  },
  {
    id: '6',
    cardNum: '5668',
    cardExpiry: '10/24',
    cardType: 'Visa',
  },
];

export const states = [
  {id: 1, name: 'Andhra Pradesh'},
  {id: 2, name: 'Arunachal Pradesh'},
  {id: 3, name: 'Assam'},
  {id: 4, name: 'Bihar'},
  {id: 5, name: 'Chhattisgarh'},
  {id: 6, name: 'Goa'},
  {id: 7, name: 'Gujarat'},
  {id: 8, name: 'Haryana'},
  {id: 9, name: 'Himachal Pradesh'},
  {id: 10, name: 'Jammu and Kashmir'},
  {id: 11, name: 'Jharkhand'},
  {id: 12, name: 'Karnataka'},
  {id: 13, name: 'Kerala'},
  {id: 14, name: 'Madhya Pradesh'},
  {id: 15, name: 'Maharashtra'},
  {id: 16, name: 'Manipur'},
  {id: 17, name: 'Meghalaya'},
  {id: 18, name: 'Mizoram'},
  {id: 19, name: 'Nagaland'},
  {id: 20, name: 'Odisha'},
  {id: 21, name: 'Punjab'},
  {id: 22, name: 'Rajasthan'},
  {id: 23, name: 'Sikkim'},
  {id: 24, name: 'Tamil Nadu'},
  {id: 25, name: 'Telangana'},
  {id: 26, name: 'Tripura'},
  {id: 27, name: 'Uttarakhand'},
  {id: 28, name: 'Uttar Pradesh'},
  {id: 29, name: 'West Bengal'},
  {id: 30, name: 'Andaman and Nicobar Islands'},
  {id: 31, name: 'Chandigarh'},
  {id: 32, name: 'Dadra and Nagar Haveli'},
  {id: 33, name: 'Daman and Diu'},
  {id: 34, name: 'Delhi'},
  {id: 35, name: 'Lakshadweep'},
  {id: 36, name: 'Puducherry'},
];
