export const AppRoute = {
  AUTH: 'AUTH',
  APP: 'APP',
  PHONE_PUB: 'PHONE_PUB',

  // TEST
  PRATIK_TEST: 'PRATIK_TEST',
  PARSHV_TEST: 'PARSHV_TEST',
  NISARG_TEST: 'NISARG_TEST',

  // AUTH ROUTES
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  SIGNUP_SCREEN: 'SIGNUP_SCREEN',
  REGISTER_PHONE_SCREEN: 'REGISTER_PHONE_SCREEN',
  FORGOT_PASSWORD_SCREEN: 'FORGOT_PASSWORD_SCREEN',
  RESET_PASSWORD_SCREEN: 'RESET_PASSWORD_SCREEN',
  OTP_SCREEN: 'OTP_SCREEN',

  // DEFAULT ROUTE
  LOGO_SCREEN: 'LOGO_SCREEN',

  // APP ROUTES
  HOME_SCREEN: 'HOME_SCREEN',
  PRODUCT_DETAIL_SCREEN: 'PRODUCT_DETAIL_SCREEN',
  CART_SCREEN: 'CART_SCREEN',
  DELIVERY_ADDRESS_SCREEN: 'DELIVERY_ADDRESS_SCREEN',

  ORDER_SCREEN: 'ORDER_SCREEN',
  ADDRESS_SCREEN: 'ADDRESS_SCREEN',
  BUY_NOW_SCREEN: 'BUY_NOW_SCREEN',
  MY_ORDER_SCREEN: 'MY_ORDER_SCREEN',
  EDIT_PROFILE_SCREEN: 'EDIT_PROFILE_SCREEN',
  ABOUT_SCREEN: 'ABOUT_SCREEN',
  CONTACT_SCREEN: 'CONTACT_SCREEN',
  RATE_SCREEN: 'RATE_SCREEN',
};
